version: '3'
services:
  pdnsdb:
    image: postgres:10
    environment:
       - POSTGRES_PASSWORD=somepassword
       - POSTGRES_USER=pdns
    network_mode: bridge
  pdnsadmindb:
    image: postgres:10
    environment:
       - POSTGRES_PASSWORD=somepassword
       - POSTGRES_USER=pdns
    network_mode: bridge
  pdns:
    build: ./pdns
    environment:
      - BACKEND=gpgsql
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=someapikey
      - PDNS_api_readonly=no
      - PDNS_webserver_password=somewebpassword
      - PDNS_webserver_allow_from=0.0.0.0/0
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=3600
      - PDNS_soa_minimum_ttl=300
      - PDNS_default_soa_name=ns@somedomain.com
      - PDNS_default_soa_mail=hostmaster.somedomain.com
    network_mode: bridge
    depends_on:
      - pdnsdb
    links:
      - pdnsdb:postgres
  pdns-admin-uwsgi:
    build: ./pdns-admin-uwsgi
    environment:
      - DBBACKEND=postgresql
    network_mode: bridge
    depends_on:
      - pdnsadmindb
      - pdns
    links:
      - pdnsadmindb:postgres
      - pdns:pdns
  pdns-admin-nginx:
    build: ./pdns-admin-nginx
    network_mode: bridge
    depends_on:
      - pdns-admin-uwsgi
    links:
      - pdns-admin-uwsgi
    ports:
      - 8880:80